const DATA="https://data.alpaca.markets";
function keys(){const key=process.env.ALPACA_API_KEY_ID||process.env.APCA_API_KEY_ID;const secret=process.env.ALPACA_API_SECRET_KEY||process.env.APCA_API_SECRET_KEY;if(!key||!secret){const e=new Error("Alpaca credentials are not configured");e.status=503;throw e}return{key,secret}}
export function tradingMode(){return(process.env.ALPACA_TRADING_MODE||"paper").toLowerCase()==="live"?"live":"paper"}
export function liveTradingAllowed(){return process.env.STONK_ALLOW_LIVE_TRADING==="I_UNDERSTAND_REAL_MONEY"}
export function tradingBase(){const mode=tradingMode();if(mode==="live"&&!liveTradingAllowed()){const e=new Error("Live trading is blocked by the Stonk safety gate");e.status=403;throw e}return mode==="live"?"https://api.alpaca.markets":"https://paper-api.alpaca.markets"}
function headers(extra={}){const{key,secret}=keys();return{"APCA-API-KEY-ID":key,"APCA-API-SECRET-KEY":secret,accept:"application/json",...extra}}
async function request(url,options={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{...options,headers:headers(options.headers),signal:c.signal});const text=await r.text();let payload=null;try{payload=text?JSON.parse(text):null}catch{payload={raw:text}}if(!r.ok){const e=new Error(payload?.message||("Alpaca request failed ("+r.status+")"));e.status=r.status;e.upstream=payload;throw e}return payload}finally{clearTimeout(t)}}
export function market(path){return request(DATA+path)}
export function trading(path,options={}){return request(tradingBase()+path,options)}
export function feed(){return process.env.ALPACA_MARKET_DATA_FEED||"indicative"}
export async function optionSnapshots(symbol,params={}){const q=new URLSearchParams({feed:feed(),limit:"1000",...Object.fromEntries(Object.entries(params).filter(([,v])=>v!==undefined&&v!==null&&v!==""))});let token="";const snapshots={};for(let page=0;page<5;page++){if(token)q.set("page_token",token);const d=await market("/v1beta1/options/snapshots/"+encodeURIComponent(symbol)+"?"+q);Object.assign(snapshots,d?.snapshots||{});token=d?.next_page_token||"";if(!token)break}return snapshots}
export async function optionContracts(symbol,params={}){const q=new URLSearchParams({underlying_symbols:symbol,status:"active",limit:"10000",...Object.fromEntries(Object.entries(params).filter(([,v])=>v!==undefined&&v!==null&&v!==""))});let token="";const out=[];for(let page=0;page<5;page++){if(token)q.set("page_token",token);const d=await trading("/v2/options/contracts?"+q);out.push(...(d?.option_contracts||[]));token=d?.next_page_token||"";if(!token)break}return out}
export async function accountSummary(){const a=await trading("/v2/account");const n=v=>Number.isFinite(Number(v))?Number(v):null;return{status:a.status,currency:a.currency,equity:n(a.equity),cash:n(a.cash),buyingPower:n(a.buying_power),optionsBuyingPower:n(a.options_buying_power),optionsApprovedLevel:a.options_approved_level,optionsTradingLevel:a.options_trading_level,patternDayTrader:a.pattern_day_trader,tradingBlocked:a.trading_blocked,transfersBlocked:a.transfers_blocked,mode:tradingMode()}}
export async function clock(){return trading("/v2/clock")}
export async function submitOrder(order){return trading("/v2/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(order)})}
