const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const num=v=>Number.isFinite(Number(v))?Number(v):null;const round=(v,d=4)=>Number(Number(v).toFixed(d));
export function normalizeChain(contracts,snapshots){return contracts.map(c=>{const s=snapshots[c.symbol]||{},q=s.latestQuote||s.latest_quote||{},g=s.greeks||{};const bid=num(q.bp??q.bid_price),ask=num(q.ap??q.ask_price),mid=bid!=null&&ask!=null&&ask>=bid?(bid+ask)/2:null,spreadPct=mid&&mid>0&&bid!=null&&ask!=null?(ask-bid)/mid:null;return{symbol:c.symbol,underlying:c.underlying_symbol,expiry:c.expiration_date,strike:num(c.strike_price),type:c.type,style:c.style,tradable:c.tradable!==false,bid,ask,mid:mid==null?null:round(mid),spreadPct:spreadPct==null?null:round(spreadPct),iv:num(s.impliedVolatility??s.implied_volatility),delta:num(g.delta),gamma:num(g.gamma),theta:num(g.theta),vega:num(g.vega),latestTrade:num((s.latestTrade||s.latest_trade||{}).p)}}).filter(x=>x.tradable&&x.strike&&x.expiry&&x.type)}
function liquidityScore(x){if(x.mid==null||x.bid==null||x.ask==null||x.mid<=0)return 0;return clamp(100-(x.spreadPct??1)*400,0,100)}
function dte(expiry,now=new Date()){return Math.max(0,Math.round((new Date(expiry+"T20:00:00Z")-now)/86400000))}
function optionQuality(x){const delta=Math.abs(x.delta??0),deltaFit=clamp(100-Math.abs(delta-.5)*180,0,100),liq=liquidityScore(x),ivPenalty=x.iv==null?10:clamp((x.iv-.85)*80,0,35);return clamp(.58*liq+.42*deltaFit-ivPenalty,0,100)}
export function scanStrategies(chain,now=new Date()){const candidates=[];for(const x of chain){const days=dte(x.expiry,now);if(days<5||days>75||x.ask==null||x.ask<=0)continue;const q=optionQuality(x);candidates.push({id:"long-"+x.symbol,strategy:x.type==="call"?"long_call":"long_put",underlying:x.underlying,expiry:x.expiry,dte:days,legs:[{symbol:x.symbol,side:"buy",position_intent:"buy_to_open",ratio_qty:"1"}],limitPrice:round(x.ask,2),maxLoss:round(x.ask*100,2),maxProfit:null,rewardRisk:null,score:round(q,1),thesis:"Directional convexity candidate; score emphasizes tradability, delta and spread quality."})}
const groups=new Map();for(const x of chain){const k=x.expiry+"|"+x.type;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)}
for(const rows of groups.values()){rows.sort((a,b)=>a.strike-b.strike);for(let i=0;i<rows.length-1;i++){for(let j=i+1;j<=Math.min(i+3,rows.length-1);j++){const low=rows[i],high=rows[j],days=dte(low.expiry,now),width=high.strike-low.strike;if(days<5||days>60||!(width>0))continue;const liq=Math.min(liquidityScore(low),liquidityScore(high));
if(low.type==="call"&&low.ask!=null&&high.bid!=null){const debit=low.ask-high.bid;if(debit>0&&debit<width){const maxLoss=debit*100,maxProfit=(width-debit)*100,rr=maxProfit/maxLoss,deltaFit=100-Math.min(100,Math.abs(Math.abs(low.delta??.5)-.55)*160),score=clamp(liq*.45+deltaFit*.25+clamp(rr*24,0,30),0,100);candidates.push({id:"bull-call-"+low.symbol+"-"+high.symbol,strategy:"bull_call_debit_spread",underlying:low.underlying,expiry:low.expiry,dte:days,legs:[{symbol:low.symbol,side:"buy",position_intent:"buy_to_open",ratio_qty:"1"},{symbol:high.symbol,side:"sell",position_intent:"sell_to_open",ratio_qty:"1"}],limitPrice:round(debit,2),maxLoss:round(maxLoss,2),maxProfit:round(maxProfit,2),rewardRisk:round(rr,2),score:round(score,1),thesis:"Defined-risk bullish vertical ranked by spread quality, delta fit and payoff asymmetry."})}}
if(low.type==="put"&&high.ask!=null&&low.bid!=null){const debit=high.ask-low.bid;if(debit>0&&debit<width){const maxLoss=debit*100,maxProfit=(width-debit)*100,rr=maxProfit/maxLoss,deltaFit=100-Math.min(100,Math.abs(Math.abs(high.delta??-.5)-.55)*160),score=clamp(liq*.45+deltaFit*.25+clamp(rr*24,0,30),0,100);candidates.push({id:"bear-put-"+low.symbol+"-"+high.symbol,strategy:"bear_put_debit_spread",underlying:low.underlying,expiry:low.expiry,dte:days,legs:[{symbol:high.symbol,side:"buy",position_intent:"buy_to_open",ratio_qty:"1"},{symbol:low.symbol,side:"sell",position_intent:"sell_to_open",ratio_qty:"1"}],limitPrice:round(debit,2),maxLoss:round(maxLoss,2),maxProfit:round(maxProfit,2),rewardRisk:round(rr,2),score:round(score,1),thesis:"Defined-risk bearish vertical ranked by spread quality, delta fit and payoff asymmetry."})}}}}}
return candidates.filter(c=>c.maxLoss==null||c.maxLoss>0).sort((a,b)=>b.score-a.score||(b.rewardRisk||0)-(a.rewardRisk||0))}
export function candidateToOrder(c,qty=1){if(!c?.legs?.length)throw new Error("Candidate has no legs");const q=Math.max(1,Math.floor(Number(qty)||1));if(c.legs.length===1)return{symbol:c.legs[0].symbol,qty:String(q),side:c.legs[0].side,type:"limit",limit_price:String(c.limitPrice),time_in_force:"day",position_intent:c.legs[0].position_intent,client_order_id:"stonk-"+Date.now()};return{order_class:"mleg",qty:String(q),type:"limit",limit_price:String(c.limitPrice),time_in_force:"day",legs:c.legs,client_order_id:"stonk-"+Date.now()}}
export function estimateOrderRisk(order){const qty=Math.max(1,Number(order.qty)||1),px=Math.abs(Number(order.limit_price)||0);if(!order.order_class||order.order_class==="simple"){if(order.side==="sell"&&order.position_intent==="sell_to_open")return{bounded:false,maxLoss:null};return{bounded:true,maxLoss:round(px*100*qty,2)}}const legs=order.legs||[];if(order.order_class!=="mleg"||legs.length<2||legs.length>4)return{bounded:false,maxLoss:null};const parsed=legs.map(l=>({...l,p:parseOcc(l.symbol)}));if(parsed.some(x=>!x.p))return{bounded:false,maxLoss:null};if(new Set(parsed.map(x=>x.p.expiry)).size!==1||new Set(parsed.map(x=>x.p.root)).size!==1)return{bounded:false,maxLoss:null};if(legs.length===2&&parsed[0].p.cp===parsed[1].p.cp){const width=Math.abs(parsed[0].p.strike-parsed[1].p.strike)*100*qty,debit=Number(order.limit_price)>=0;return{bounded:true,maxLoss:round(debit?px*100*qty:Math.max(0,width-px*100*qty),2)}}if(legs.length===4){const calls=parsed.filter(x=>x.p.cp==="C").sort((a,b)=>a.p.strike-b.p.strike),puts=parsed.filter(x=>x.p.cp==="P").sort((a,b)=>a.p.strike-b.p.strike);if(calls.length===2&&puts.length===2){const width=Math.max(Math.abs(calls[1].p.strike-calls[0].p.strike),Math.abs(puts[1].p.strike-puts[0].p.strike))*100*qty,debit=Number(order.limit_price)>=0;return{bounded:true,maxLoss:round(debit?px*100*qty:Math.max(0,width-px*100*qty),2)}}}return{bounded:false,maxLoss:null}}
export function parseOcc(symbol){const m=String(symbol).match(/^([A-Z0-9.]{1,8})(\d{6})([CP])(\d{8})$/);if(!m)return null;return{root:m[1],expiry:"20"+m[2].slice(0,2)+"-"+m[2].slice(2,4)+"-"+m[2].slice(4,6),cp:m[3],strike:Number(m[4])/1000}}
