begin;

-- Sourced company profile
insert into public.research_companies
  (ticker, name, exchange, sector, description, source_url, as_of, coverage_note, coverage_source_url)
values ('CDW', 'CDW Corporation', 'NASDAQ', 'Information Technology · IT solutions distribution and services', 'CDW distributes and integrates multi-brand information technology products and services for business, government, education and healthcare customers in the United States, United Kingdom and Canada. Its 2025 Form 10-K reported more than 250,000 customers and approximately 14,800 coworkers.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', '2026-09-29', 'This is a sourced sample of CDW''s network, not a complete customer or supplier roster. CDW reports more than 1,000 vendor partners and more than 250,000 customers. Many customers are confidential. Named sell-side analysts are omitted because no current primary-source roster was verified. Ownership snapshots are dated filings, not real-time positions.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm')
on conflict (ticker) do update set
  name = excluded.name, exchange = excluded.exchange, sector = excluded.sector,
  description = excluded.description, source_url = excluded.source_url,
  as_of = excluded.as_of, coverage_note = excluded.coverage_note,
  coverage_source_url = excluded.coverage_source_url, updated_at = now();

-- Replace only this company's curated relationship snapshot.
delete from public.research_relationships where company_ticker = 'CDW';

-- Relationships are keyed by company, section and source-list position.
insert into public.research_relationships
  (id, company_ticker, section, name, related_ticker, detail, source_url, source_label, as_of, status)
values
  ('CDW:suppliers:0001', 'CDW', 'suppliers', 'Adobe', 'ADBE', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0002', 'CDW', 'suppliers', 'Apple', 'AAPL', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0003', 'CDW', 'suppliers', 'Amazon Web Services', 'AMZN', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0004', 'CDW', 'suppliers', 'Cisco', 'CSCO', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0005', 'CDW', 'suppliers', 'Dell Technologies', 'DELL', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0006', 'CDW', 'suppliers', 'Hewlett Packard Enterprise', 'HPE', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0007', 'CDW', 'suppliers', 'HP Inc.', 'HPQ', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0008', 'CDW', 'suppliers', 'IBM', 'IBM', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0009', 'CDW', 'suppliers', 'Intel', 'INTC', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0010', 'CDW', 'suppliers', 'Lenovo', null, 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0011', 'CDW', 'suppliers', 'Microsoft', 'MSFT', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0012', 'CDW', 'suppliers', 'Nvidia', 'NVDA', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0013', 'CDW', 'suppliers', 'Palo Alto Networks', 'PANW', 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0014', 'CDW', 'suppliers', 'Samsung', null, 'Named by CDW among its vendor partners in its 2025 Form 10-K. A vendor/brand relationship does not disclose an individual purchasing contract or spend for this name.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Partners', '2026-02-20', 'vendor partner'),
  ('CDW:suppliers:0015', 'CDW', 'suppliers', 'Ingram Micro', 'INGM', 'Wholesale distributor. CDW says purchases from these two distributors together exceeded 25% of total purchases; the individual split is not disclosed.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Supply risk', '2026-02-20', 'wholesale distributor'),
  ('CDW:suppliers:0016', 'CDW', 'suppliers', 'TD SYNNEX', 'SNX', 'Wholesale distributor. CDW says purchases from these two distributors together exceeded 25% of total purchases; the individual split is not disclosed.', 'https://www.sec.gov/Archives/edgar/data/1402057/000140205726000011/cdw-20251231.htm', 'CDW 2025 Form 10-K · Supply risk', '2026-02-20', 'wholesale distributor'),
  ('CDW:customers:0001', 'CDW', 'customers', 'Precision Cable Assemblies', null, 'Named CDW customer; CDW designed an Azure environment for the company''s ERP migration.', 'https://www.cdw.com/content/cdw/en/articles/hardware/building-foundation-cloud-success.html', 'CDW customer case study', '2025-08-29', 'public case study'),
  ('CDW:customers:0002', 'CDW', 'customers', 'Jim''s Formal Wear', null, 'Named CDW customer; worked with CDW on a Google Cloud migration.', 'https://www.cdw.com/content/cdw/en/articles/cloud/ibm-power-google-cloud-with-cdws-expertise.html', 'CDW customer case study', '2025-01-01', 'public case study'),
  ('CDW:customers:0003', 'CDW', 'customers', 'We Insure', null, 'Named CDW customer; CDW helped optimize its Amazon Connect contact center.', 'https://www.cdw.com/content/cdw/en/articles/digitalworkspace/cdw-helps-insurance-company-transform-contact-center.html', 'CDW customer case study', '2026-07-15', 'public case study'),
  ('CDW:customers:0004', 'CDW', 'customers', 'Southwest Service Administrators', null, 'Named CDW customer in a Zoom unified communications case study.', 'https://www.cdw.com/content/cdw/en/articles/digitalworkspace/one-small-business-improve-customer-service-modern-contact-center.html', 'CDW customer case study', '2026-02-09', 'public case study'),
  ('CDW:indices:0001', 'CDW', 'indices', 'S&P 500 Index', null, 'CDW identifies itself as a member of the S&P 500 Index on its investor relations site.', 'https://investor.cdw.com/overview/', 'CDW investor relations', '2026-09-29', 'company-reported membership'),
  ('CDW:competitors:0001', 'CDW', 'competitors', 'Insight Enterprises', 'NSIT', 'Fellow IT solutions provider. Connection''s 2025 annual report identifies CDW and Insight as national competitors; Insight also names CDW as a competitor.', 'https://www.sec.gov/Archives/edgar/data/1050377/000110465926036111/cnxn-20251231xars.pdf', 'Connection 2025 annual report · Competition', '2026-03-27', 'named peer'),
  ('CDW:competitors:0002', 'CDW', 'competitors', 'Connection', 'CNXN', 'Connection identifies CDW as a competing national IT solutions provider in its 2025 annual report.', 'https://www.sec.gov/Archives/edgar/data/1050377/000110465926036111/cnxn-20251231xars.pdf', 'Connection 2025 annual report · Competition', '2026-03-27', 'named peer'),
  ('CDW:competitors:0003', 'CDW', 'competitors', 'SHI International', null, 'Privately held IT solutions provider named alongside CDW as a national competitor by Connection.', 'https://www.sec.gov/Archives/edgar/data/1050377/000110465926036111/cnxn-20251231xars.pdf', 'Connection 2025 annual report · Competition', '2026-03-27', 'named peer'),
  ('CDW:holders:0001', 'CDW', 'holders', 'Vanguard Capital Management', null, 'Schedule 13G reports 9,747,914 shares, 7.57% beneficial ownership as of March 31, 2026. Reported separately after Vanguard Group disaggregated its ownership; do not add to old parent-company figure.', 'https://www.sec.gov/Archives/edgar/data/1402057/000210011926000331/xslSCHEDULE_13G_X02/primary_doc.xml', 'SEC Schedule 13G · Vanguard Capital Management', '2026-03-31', 'filed ownership snapshot'),
  ('CDW:holders:0002', 'CDW', 'holders', 'Vanguard Portfolio Management', null, 'Schedule 13G reports 8,200,432 shares, 6.37% beneficial ownership as of March 31, 2026. Separately reported business unit after Vanguard Group disaggregation; do not assume figures across Vanguard filings are additive.', 'https://www.sec.gov/Archives/edgar/data/1402057/000210012126000172/xslSCHEDULE_13G_X02/primary_doc.xml', 'SEC Schedule 13G · Vanguard Portfolio Management', '2026-03-31', 'filed ownership snapshot'),
  ('CDW:board:0001', 'CDW', 'board', 'Christine A. Leahy', null, 'Chair, President and Chief Executive Officer. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:board:0002', 'CDW', 'board', 'Virginia C. Addicott', null, 'Director; former CEO, FedEx Custom Critical. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:board:0003', 'CDW', 'board', 'James A. Bell', null, 'Lead Independent Director; former Boeing CFO. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:board:0004', 'CDW', 'board', 'Lynda M. Clarizio', null, 'Director; co-founder, The 98. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:board:0005', 'CDW', 'board', 'Anthony R. Foxx', null, 'Director; former U.S. Secretary of Transportation. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:board:0006', 'CDW', 'board', 'Kelly J. Grier', null, 'Director; former U.S. Chair and Managing Partner, EY. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:board:0007', 'CDW', 'board', 'Marc E. Jones', null, 'Director; Aeris Communications chairman and CEO emeritus. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:board:0008', 'CDW', 'board', 'David W. Nelms', null, 'Director; former Discover Financial Services CEO. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:board:0009', 'CDW', 'board', 'Joseph R. Swedish', null, 'Director; former Anthem CEO. Listed on CDW''s current leadership page and in its 2026 proxy.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Board', '2026-09-29', 'public board member'),
  ('CDW:leadership:0001', 'CDW', 'leadership', 'Christine A. Leahy', null, 'Chair, President and Chief Executive Officer. Listed by CDW as a member of its Enterprise Operating Committee.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Enterprise Operating Committee', '2026-09-29', 'public executive'),
  ('CDW:leadership:0002', 'CDW', 'leadership', 'Elizabeth H. Connelly', null, 'Chief Commercial Officer and Executive Vice President. Listed by CDW as a member of its Enterprise Operating Committee.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Enterprise Operating Committee', '2026-09-29', 'public executive'),
  ('CDW:leadership:0003', 'CDW', 'leadership', 'Rick Kulevich', null, 'Chief Legal Officer and Executive Vice President, Risk and Compliance, and Corporate Secretary. Listed by CDW as a member of its Enterprise Operating Committee.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Enterprise Operating Committee', '2026-09-29', 'public executive'),
  ('CDW:leadership:0004', 'CDW', 'leadership', 'Mukesh Kumar', null, 'Chief Services and Solutions Officer and Executive Vice President. Listed by CDW as a member of its Enterprise Operating Committee.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Enterprise Operating Committee', '2026-09-29', 'public executive'),
  ('CDW:leadership:0005', 'CDW', 'leadership', 'Albert J. Miralles', null, 'Chief Financial Officer and Executive Vice President, Enterprise Business Operations. Listed by CDW as a member of its Enterprise Operating Committee. CDW announced in August 2026 that he intends to retire in 2027 after a successor is named.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Enterprise Operating Committee', '2026-09-29', 'public executive'),
  ('CDW:leadership:0006', 'CDW', 'leadership', 'Kate Sanderson', null, 'Chief Human Resources Officer and Executive Vice President, Coworker Success. Listed by CDW as a member of its Enterprise Operating Committee.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Enterprise Operating Committee', '2026-09-29', 'public executive'),
  ('CDW:leadership:0007', 'CDW', 'leadership', 'Hang Tan', null, 'Chief Strategy and Transformation Officer and Executive Vice President. Listed by CDW as a member of its Enterprise Operating Committee.', 'https://www.cdw.com/content/cdw/en/about/overview/our-leadership.html', 'CDW leadership · Enterprise Operating Committee', '2026-09-29', 'public executive')
on conflict (id) do update set
  name = excluded.name, related_ticker = excluded.related_ticker, detail = excluded.detail,
  source_url = excluded.source_url, source_label = excluded.source_label,
  as_of = excluded.as_of, status = excluded.status, updated_at = now();

commit;
