const $=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));let symbol="SPY";
async function api(path){const r=await fetch(path,{headers:{accept:"application/json"}}),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.error||("Request failed "+r.status));return j}
function money(v){return v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v)}
function metric(label,value){return '<div class="metric"><span class="muted">'+esc(label)+'</span><b>'+esc(value)+'</b></div>'}
function rows(items,fmt){return(items||[]).map(fmt).join("")||'<div class="muted">No data</div>'}
function setTab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x.dataset.tab===id))}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
async function health(){try{const h=await api("/api/health");$("#status").textContent=h.mode.toUpperCase()+" · "+(h.alpacaConfigured?"DATA READY":"NO KEYS");$("#automationState").innerHTML=metric("Trading mode",h.mode)+metric("Live gate",h.liveTradingAllowed?"enabled":"blocked")+metric("Auto scan",h.autoTradeEnabled?"enabled":"disabled")+metric("Auto execute",h.autoTradeExecute?"enabled":"disabled")}catch{$("#status").textContent="offline"}}
async function loadMarket(){try{const d=await api("/api/market");$("#gainers").innerHTML=rows(d.movers?.gainers,x=>'<div class="row"><b>'+esc(x.symbol)+'</b><span>+'+Number(x.percent_change||0).toFixed(2)+'%</span></div>');$("#losers").innerHTML=rows(d.movers?.losers,x=>'<div class="row"><b>'+esc(x.symbol)+'</b><span>'+Number(x.percent_change||0).toFixed(2)+'%</span></div>');$("#actives").innerHTML=rows(d.actives?.most_actives,x=>'<div class="row"><b>'+esc(x.symbol)+'</b><span>'+Number(x.volume||0).toLocaleString()+'</span></div>')}catch(e){$("#gainers").innerHTML='<div class="muted">'+esc(e.message)+'</div>'}}
async function options(){$("#candidates").innerHTML='<tr><td colspan="7">Scanning…</td></tr>';try{const d=await api("/api/options?symbol="+encodeURIComponent(symbol)+"&minDte=7&maxDte=45"),s=d.signal||{};$("#optionSummary").innerHTML=metric("Ticker",d.symbol)+metric("Trend",String(s.direction||"neutral").toUpperCase())+metric("Signal confidence",(s.confidence??0)+"%")+metric("5D return",s.return5==null?"—":(s.return5*100).toFixed(2)+"%")+metric("20D return",s.return20==null?"—":(s.return20*100).toFixed(2)+"%")+metric("Realized vol",s.realizedVol==null?"—":(s.realizedVol*100).toFixed(1)+"%")+metric("Contracts",d.contractCount)+metric("Candidates",d.candidates.length);$("#candidates").innerHTML=d.candidates.slice(0,30).map(c=>'<tr><td><b>'+esc(c.score)+'</b></td><td>'+esc(c.strategy)+'</td><td>'+esc(c.expiry)+' ('+c.dte+'d)</td><td>'+money(c.limitPrice)+'</td><td>'+money(c.maxLoss)+'</td><td>'+money(c.maxProfit)+'</td><td>'+esc(c.rewardRisk??"—")+'</td></tr>').join("")||'<tr><td colspan="7">No liquid defined-risk candidates found.</td></tr>'}catch(e){$("#candidates").innerHTML='<tr><td colspan="7">'+esc(e.message)+'</td></tr>'}}
async function intelligence(){try{const d=await api("/api/intelligence?symbol="+encodeURIComponent(symbol));if(d.macro){$("#macroCards").innerHTML=Object.values(d.macro).map(x=>metric(x.label,x.observation?x.observation.value+" · "+x.observation.date:"—")).join("")}else{$("#macroCards").innerHTML=metric("FRED macro",d.macroConfigured?(d.macroError||"unavailable"):"add FRED_API_KEY")}$("#news").innerHTML=rows(d.news,x=>'<div class="row"><div><b>'+esc(x.headline||"Untitled")+'</b><div class="muted">'+esc(x.source||"")+'</div></div><span>'+esc(String(x.created_at||"").slice(0,10))+'</span></div>');const buckets=d.corporateActions||{};const all=Object.entries(buckets).flatMap(([type,items])=>(items||[]).map(x=>({type,...x})));$("#actions").innerHTML=rows(all.slice(0,25),x=>'<div class="row"><b>'+esc(x.type.replaceAll("_"," "))+'</b><span>'+esc(x.ex_date||x.process_date||x.declaration_date||"")+'</span></div>')}catch(e){$("#news").innerHTML='<div class="muted">'+esc(e.message)+'</div>'}}
async function research(){$("#filings").innerHTML="Loading SEC data…";try{const d=await api("/api/research?symbol="+encodeURIComponent(symbol)),m=d.metrics||{};$("#facts").innerHTML=metric("Company",d.name)+metric("Revenue",m.revenue?money(m.revenue.value):"—")+metric("Net income",m.netIncome?money(m.netIncome.value):"—")+metric("Assets",m.assets?money(m.assets.value):"—")+metric("Cash",m.cash?money(m.cash.value):"—");$("#filings").innerHTML=rows(d.filings,f=>'<div class="row"><b>'+esc(f.form)+'</b><span>'+esc(f.filed||"")+' · '+esc(f.reportDate||"")+'</span></div>')}catch(e){$("#filings").innerHTML='<div class="muted">'+esc(e.message)+'</div>'}}
async function account(){try{const d=await api("/api/account"),a=d.account;$("#accountCards").innerHTML=metric("Mode",a.mode)+metric("Equity",money(a.equity))+metric("Day P/L",money(a.dayPnL))+metric("Cash",money(a.cash))+metric("Buying power",money(a.buyingPower))+metric("Options BP",money(a.optionsBuyingPower))+metric("Options level",a.optionsTradingLevel??"—")+metric("Trading blocked",String(a.tradingBlocked))}catch(e){$("#accountCards").innerHTML=metric("Broker",e.message)}}
$("#symbolForm").onsubmit=e=>{e.preventDefault();symbol=$("#symbol").value.trim().toUpperCase()||"SPY";setTab("options");options()};$("#refreshMarket").onclick=loadMarket;$("#scanOptions").onclick=options;$("#loadIntelligence").onclick=intelligence;$("#loadResearch").onclick=research;$("#loadAccount").onclick=account;health();loadMarket();
